Repository kosa-project-web/game, pull requests merged in 2024-08, with the labels that each got.

#2 깃 연결하기
  index.html
Labels: enhancement

#4 인덱스 페이지 제작
  css/common/styles.css
  css/index.css
  img/common/broken-heart.png
  img/common/heart.png
  img/common/home.png
  img/common/info.png
  img/common/lose.png
  img/common/restart.png
  img/common/stop.png
  img/common/time.png
  img/common/win.png
  img/index/bulls-and-cows.png
  img/index/card-matching.png
  img/index/down-arrow.png
  img/index/find-different-color.png
  img/index/memory-test.png
  img/index/question.png
  img/index/rock-paper-scissors.png
  index.html
  js/index.js
  resources/favicon/favicon.ico
Labels: enhancement

#9 유즈 케이스 작성하기
  use-case.svg
Labels: documentation

#10 가위바위보 게임 만들기
  css/game-rps.css
  game-rps.html
  img/game-rps/paper.png
  img/game-rps/rock.png
  img/game-rps/scissors.png
  js/game-rps.js
Labels: enhancement

#13 카드 짝 맞추기 게임 만들기
  css/game-cm.css
  game-cm.html
  img/game-cm/card-pack/bear.png
  img/game-cm/card-pack/camel.png
  img/game-cm/card-pack/cat.png
  img/game-cm/card-pack/chick.png
  img/game-cm/card-pack/chicken.png
  img/game-cm/card-pack/cockroach.png
  img/game-cm/card-pack/cow.png
  img/game-cm/card-pack/dolphin.png
  img/game-cm/card-pack/elephant.png
  img/game-cm/card-pack/fish.png
  img/game-cm/card-pack/frog.png
  img/game-cm/card-pack/horse.png
  img/game-cm/card-pack/kitty.png
  img/game-cm/card-pack/koala.png
  img/game-cm/card-pack/monkey.png
  img/game-cm/card-pack/penguin.png
  img/game-cm/card-pack/pig.png
  img/game-cm/card-pack/porcupine.png
  img/game-cm/card-pack/puffer-fish.png
  img/game-cm/card-pack/rabbit.png
  img/game-cm/card-pack/rat-head.png
  img/game-cm/card-pack/shell.png
  img/game-cm/card-pack/snail.png
  img/game-cm/card-pack/snake.png
  img/game-cm/card-pack/squid.png
  img/game-cm/card-pack/tiger.png
  img/game-cm/card-pack/whale.png
  img/game-cm/clear.png
  img/game-cm/pawprint.png
  js/game-cm.js
Labels: enhancement

#14 기억력 테스트 게임 만들기
  .idea/.gitignore
  .idea/game.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  css/game-mt.css
  game-mt.html
  img/game-mt/clear.png
  img/game-mt/turn.png
  js/game-mt.js
Labels: enhancement

#15 야구 게임
  .idea/.gitignore
  .idea/dbnavigator.xml
  .idea/game.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  css/game-bac.css
  game-bac.html
  js/game-bac.js
Labels: enhancement

#17 다른색 찾기
  .idea/mini_project_webb.iml
  .idea/misc.xml
  .idea/modules.xml
  css/game-fdc.css
  game-fdc.html
  js/game-fdc.js
  resources/game-fdc.html
Labels: enhancement

#21 유즈 케이스 업데이트
  .idea/.gitignore
  .idea/dbnavigator.xml
  .idea/game.iml
  .idea/mini_project_webb.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: documentation

#23 유즈 케이스 업로드
  .DS_Store
  doc/use-case.svg
Labels: documentation

#26 다른색 찾기 랭킹
  css/game-fdc.css
  game-fdc.html
  js/game-fdc.js
Labels: enhancement

#27 #18-gmae-mt 닉네임 등록 및 랭킹 조회
  game-mt.html
  js/game-mt.js
Labels: enhancement

#29 가위바위보 랭킹 작업
  css/game-rps.css
  game-rps.html
  js/game-rps.js
Labels: enhancement

#32 카드 짝 맞추기 랭킹 작업
  css/game-cm.css
  game-cm.html
  js/game-cm.js
Labels: enhancement

#35 가위바위보 게임 코드 수정
  game-rps.html
  js/game-rps.js
Labels: bug, enhancement

#36 Feature/#31 game mt modify code
  game-mt.html
  js/game-mt.js
Labels: enhancement

#38 인덱스 페이지 디자인 변경
  js/index.js
Labels: enhancement
